### ISSUE TITLE
update currentSite to match 404 and 500 pages

### ISSUE THREAD

**Issue by tobeycodes** [10up/headstartwp#251]
404 and 500 pages do not sit under the `_sites/[site]` middleware so do not have access to the query param. The site can be set here with the `window.location.host` value instead.

```
const currentSite = useMemo(() => {
	if (router.query?.site && !Array.isArray(router.query.site)) {
		return getSiteByHost(router.query.site, router.locale);
	}

	// 404.js and 500.js do not have a site query param.
	if (typeof window !== 'undefined') {
		return getSiteByHost(window.location.host, router.locale);
	}

	return {};
}, [router]);
```

**Comment by steven-tey** [comment]
The Platforms Starter Kit now supports [custom 404 pages](https://twitter.com/steventey/status/1676656951852417024) <picture data-single-emoji=":love-cry:" title=":love-cry:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/love-cry/322498a74cf097e5.png" alt=":love-cry:" align="absmiddle"></picture>

**Comment by nicholasio** [comment]
With our upcoming release o app router this is now supported inside app router!
