### ISSUE TITLE
Duplication of Meta Description Tags and Canonical Links

### ISSUE THREAD

**Issue by mnagdycnn** [10up/headstartwp#495]
### Describe the bug

This [feature](https://github.com/10up/headstartwp/blob/develop/packages/next/src/components/Yoast.tsx#L109:L134) in the framework the `key` attribute is supposed to prevent duplication of both meta description tags and canonical links. However, it does not in this case in .

This could be due to the position of GTM tags in `<Head />` component in `_document.js` in `nextjs/src/pages`. However, when applied the solution for meta description tags as follows:
```JS

<Head>
      {/* Added dynamic meta tag with a key to prevent duplication in Head component */}
      <meta
	      key="description"
	      name="description"
	      content={metaDescription || defaultMetaDescription}
      />	
</Head>
```

It solved the issue. Tried the same with the canonicals as for adding a key it did not solve anything. It even added more duplicate canonical links. 

Nevertheless, both issues should've been solved by the first link mentioned above I believe.

### Steps to Reproduce

1. Add GTM tags in the `_document.js` in the `<Head />` component in `nextjs/src/pages`
2. Go to Google Chrome Browser and open up the "Developer Tools"
3. Move from one page to another at least 3 times ( for example from Homepage -> Article page 1 -> Article page 2)
4. You will notice that the homepage meta description tags and/or the canonical links are saved from the first page your were on in the previous example ( The Homepage)

### Environment information

- Device: MacBook Pro (16-inch, 2019)
- OS: macOS Monterey 12.6.1
- Browser: Google Chrome Version 114.0.5735.106 (Official Build) (x86_64)

### WordPress information

Version | 6.1.3 (Latest version: 6.2.2)
-- | --
Site Language | en_US
User Language | en_US
Timezone | +04:00
Permalink structure | /%postname%/
Is this site using HTTPS? | Yes
Is this a multisite? | No
Can anyone register on this site? | No
Is this site discouraging search engines? | No
Default comment status | Open
Environment type | production
User count | 969
Communication with WordPress.org | WordPress.org is reachable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
Thanks for the bug report. I'll try to reproduce this issue in the test project and see if I can isolate the source cause of the issue.

**Comment by nicholasio** [comment]
@mnagdycnn Just confirm if we can close this. As we chatted in slack you were able to fix this by switching to `useYoastHtml` option in `HeadlessApp` component in `_app.js`.

**Comment by mnagdycnn** [comment]
Yes! Thank you @nicholasio
