### ISSUE TITLE
wpKsesPost is bypassing certain paramaters due to the svg support

### ISSUE THREAD

**Issue by devinle** [10up/headstartwp#503]
### Describe the bug

The wpKsesPost is not working. I would expect it to allow the target attribute on an <a> element, but it removes it by default.

### Steps to Reproduce

1. Take the html of an <a> element that contains target.
2. Pass it through the wpKsesPost method
`wpKsesPost(html, ksesAllowedList);`
3. Notice the rel and target are removed
4. Now update the method to use
`wpKsesPost(html, ksesAllowedList, {svg: false})`
5. Notice the target now outputs properly

It seems the svg logic [here](https://github.com/10up/headstartwp/blob/develop/packages/core/src/dom/wpKsesPost.ts#L52) is preventing the addition of target. 

In order for me to allow for target and rel attributes in my local setup, I had to add to the wpKsesPost method as follows:

```
sanitizeFn={(html) => {
    return wpKsesPost(
        html,
        { ...ksesAllowedList, a: [...ksesAllowedList.a, 'target', 'rel'] },
        { css: false, svg: false },
    );
}}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
This has been fixed in the latest version. There are a few more things we're addressing in https://github.com/10up/headstartwp/issues/496 but your issue should be already fixed in the latest version.
