### ISSUE TITLE
Youtube iframes not working

### ISSUE THREAD

**Issue by mnagdycnn** [10up/headstartwp#505]
### Describe the bug

As I include YouTube iframes into posts. They tend to give an _"Application error"_ from the nextjs side. As I dug deeper into the issue it turns out that the problem is related to the regex that extracts video id and the title. This [piece](https://github.com/10up/headstartwp/blob/develop/packages/core/src/dom/index.ts#L143:L144). It gives me an error of _"match of undefined"_

For anyone facing this issue a temporary solution could be removing the `<YoutubeLiteBlock />` as it looks for iframes and tries to extract the video id and title of the YouTube video.

### Steps to Reproduce

1. Create a post 
2. Embed a Youtube iframe into a shortcode block ( make sure it's allowed in Wordpress allowed list first )
3. Use this block of code in your blocks component in your react or nextjs app to reproduce the issue
```JS
<BlocksRenderer
		html={html}
		ksesAllowList={{
		    ...ksesAllowedList,
			}}
		>
		<YoutubeLiteBlock />
</BlocksRenderer>
```
5. You will notice that the page is not loading and giving "Application error"

### Environment information

- Device: MacBook Pro (16-inch, 2019)
- OS: macOS Monterey 12.6.1
- Browser: Google Chrome Version 114.0.5735.106 (Official Build) (x86_64)

### WordPress information

<!DOCTYPE html>

Version | 6.1.3 (Latest version: 6.2.2)
-- | --
Site Language | en_US
User Language | en_US
Timezone | +04:00
Permalink structure | /%postname%/
Is this site using HTTPS? | Yes
Is this a multisite? | No
Can anyone register on this site? | No
Is this site discouraging search engines? | No
Default comment status | Open
Environment type | production
User count | 969
Communication with WordPress.org

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
Thanks for the report. Fixed in the attached PR. Will be released soon.
