### ISSUE TITLE
Edit this page like give 404 response

### ISSUE THREAD

**Issue by mohmed98** [10up/headstartwp#536]
### Describe the bug

When trying to edit any documentation page, I received a GitHub 404 response.

### Steps to Reproduce

1. Any documentation page
2. Press on edit this page link at the bottom of the page
3. You will get 404 response 

### Screenshots, screen recording, code snippet

screen recording: https://d.pr/v/PWcXtC

### Environment information

- Device: Dell G15
- Os: Ubuntu
- Browser: Chrome Version 114.0.5735.198 (Official Build) (64-bit)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
This has been fixed.
