### ISSUE TITLE
Getting TypeError: fetch failed

### ISSUE THREAD

**Issue by mohmed98** [10up/headstartwp#538]
### Describe your question

Hello, I am stuck and can't figure out what I missed in setting up the project, here is what I did so far:

- Used  "npx create-next-app --use-npm -e https://github.com/10up/headstartwp/tree/trunk/projects/wp-nextjs"
- Added my .env variables 
![image](https://github.com/10up/headstartwp/assets/43110858/39b61d7d-a83e-4077-88c9-5f1393420d2c)

-  Installed the plugin manually because didn't understand where to add composer config
![image](https://github.com/10up/headstartwp/assets/43110858/8fbf81b2-0b29-4723-b0bc-8fea4413b395)

- also getting this error in terminal 
 ![image](https://github.com/10up/headstartwp/assets/43110858/4a2026f7-c0fc-43f7-9a33-73fa208b3e7e)
Hope these screenshot helps, and thanks in advance

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
Are you using node 18 on mac os? I'm also having this issue and not 100% what's going on. It's something related to node 18 running locally on mac os. Does it work with node 16 for you?

The workaround for me is to comment this line on my /etc/hosts `# ::1             localhost` file.

Seems to be related to this https://github.com/nodejs/node/issues/46167

**Comment by nicholasio** [comment]
On your .env file HOST_URL should point to the next.js host url

**Comment by riccardodicurti** [comment]
Hi, I had the same problem as you with node 18.X using macos. I can confirm that also in my case node 16.X solved the problem.

**Comment by mohmed98** [comment]
I have commented the  /etc/hosts # ::1   localhost
![image](https://github.com/10up/headstartwp/assets/43110858/e7863dc1-631d-4ef9-ae0e-40b1e1fbc7ce)
 
Made my .env file HOST_URL should point to the next.js host URL
![image](https://github.com/10up/headstartwp/assets/43110858/e659a648-a022-4e84-9151-634a7abd3402)

Downgraded my node version to 16
![image](https://github.com/10up/headstartwp/assets/43110858/c8f890ee-2af3-4aeb-bf2e-6c6343b03a3a)

Still getting same error
![image](https://github.com/10up/headstartwp/assets/43110858/2a21bcb9-dae9-4ee2-8b4e-68dfd8af8a1f)

My OS is Ubuntu 22.04.2 LTS

**Comment by nicholasio** [comment]
It sounds like next.js didn't pick up your env variables. Can you try `rm -rf .next && npm run dev` to see if after a clean build it works for you?

**Comment by mohmed98** [comment]
Just tried and same error
![image](https://github.com/10up/headstartwp/assets/43110858/71a11437-e55f-43d5-8e19-8e912630eb5c)

**Comment by mohmed98** [comment]
It worked, just after deleting .env.development file. Thank you, @nicholasio and @riccardodicurti for your help :pray: 
![image](https://github.com/10up/headstartwp/assets/43110858/0d7c3766-d02f-4e52-9d5c-00052b1246cf)

**Comment by Sidsector9** [comment]
Faced the same issue on MacOS. The only solution that worked for me was to delete the `.env.development` file.
