### ISSUE TITLE
Update Search Strategy to use the native REST API search endpoint

### ISSUE THREAD

**Issue by nicholasio** [10up/headstartwp#546]
### Is your enhancement related to a problem? Please describe.

Currently, we're using the endpoint of the post type being queried for when running search queries. This means search can only search for one post type at a time.

The [WordPress REST API Search Results endpoint](https://developer.wordpress.org/rest-api/reference/search-results/) is much more flexible allowing search across multiple object types. However, it won't retrieve the full post object like it currently does for useSearch, usePost, and usePosts. 

This isn't necessarily a problem since when rendering search results we might not need all of the post info. However, it's likely very common to need things like tags names and other embedded data that won't be available by default in the REST API response, we could however, extend the WordPress this endpoint to include all of the embedded data.

We need to look into our options and come up with a better approach to search. No matter what we do, the current search strategy should remain the same. If we introduce a new strategy we could toggle the new strategy via a option/flag in the `useSearch` hook.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnwatkins0** [comment]
Picking this up. Will follow up by the end of this week.

**Comment by johnwatkins0** [comment]
Got set up locally and started looking into this, but haven't gotten far yet. If anyone sees this and is eager to pick up this issue, feel free to chime in; otherwise I'll be digging in more next week.

**Comment by nicholasio** [comment]
Reassigning this to @lucymtc as shell have resourcing to pick this up on January,
