### ISSUE TITLE
Add additional classes on Menu

### ISSUE THREAD

**Issue by burhandodhy** [10up/headstartwp#570]
### Is your enhancement related to a problem? Please describe.

At the moment, the menu item only has one class related to its depth. It would be beneficial to include additional classes such as `menu-item-type-custom` and `menu-item-has-children`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
We haven't actually used this component in production, but happy to add improvements to it. Wanna submit a PR?
