### ISSUE TITLE
"Redirect to Headless Site?" option is enabled by default and interacts poorly with object-cache 

### ISSUE THREAD

**Issue by dustinrue** [10up/headstartwp#573]
### Describe the bug

When enabling the plugin, the redirect to the headless URL is checked by default. Unchecking it and saving results in expected behavior, but visiting the options page again will show the option as enabled. Clearing object cache will allow the options page to show the correct underlying value.

### Steps to Reproduce

1. Add the plugin via preferred method
2. Enable the plugin
3. Unexpectedly break your site because it redirects to localhost
4. Uncheck the option, click save
5. Visiting the page again shows the option as checked.

### Environment information

macOS
node 16
latest plugin form composer
latest example cost from guide

### WordPress information

WP 6.3
PHP 8.1
cloudflare with APO enabled/active
theme is flat

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
We don't do any caching on these settings. https://github.com/10up/headstartwp/blob/develop/wp/headless-wp/includes/classes/Plugin.php#L199C53-L199C53

@orballo would you mind double checking this and see if you can reproduce?

**Comment by dustinrue** [comment]
I couldn't replicate this with a fresh install of WP with the default theme, so like my other issue I think this might be related to my env or theme. I can dig into it more.

**Comment by orballo** [comment]
I cannot reproduce this issue in a new install using Local:

> Unexpectedly break your site because it redirects to localhost

Just a nitpick here, that the site won't break until you set the Headless Frontend URL.
