### ISSUE TITLE
Following the guide results in an error in the production build

### ISSUE THREAD

**Issue by dustinrue** [10up/headstartwp#574]
### Describe the bug

After following the quick setup guide and using:

`npx create-next-app --use-npm -e https://github.com/10up/headstartwp/tree/trunk/projects/wp-nextjs`

modifying the necessary .env values and then performing:

* npm run build
* npm start

I get this error:

```
> @10up/wp-nextjs@0.2.0 start
> next start

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
[Error: ENOENT: no such file or directory, open '/Users/dustin/Development/personal/my-app/.next/prerender-manifest.json'] {
  type: 'Error',
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/dustin/Development/personal/my-app/.next/prerender-manifest.json'
}
```

I checked the .next directory and it is indeed not there.

Also, during the build I get this error for a few pages and I assume it is related to my theme being "flat":

```
Error occurred prerendering page "/proxmox-cloud-init". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'length')
```

### Steps to Reproduce

1. Follow the quick setup guide
2. Install the WP plugin
3. Copy/pasta the npx create command
4. Configure .env to point at correct backend URL
5. Run npm run build (I do get errors for _some_ pages but not all)
6. Run npm start
7. Get error

### Environment information

macOS
node 16

### WordPress information

WP 6.3
PHP 8.1
cloudflare with APO enabled/active
theme flat

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dustinrue** [comment]
I could not replicate this issue when I connected the code to a fresh install of WP using the default theme. I feel like this is an env issue on my side or something to do with my theme. I'll try to dig in on my own.

**Comment by nicholasio** [comment]
@dustinrue is this an actual issue or can we close this?

**Comment by dustinrue** [comment]
You can safely ignore me, I'll close this out.
