### ISSUE TITLE
Upgrade to Node v18

### ISSUE THREAD

**Issue by tobeycodes** [10up/headstartwp#594]
### Is your enhancement related to a problem? Please describe.

Currently the `.nvmrc` is set to 16. Since Node v16 is nearing end of life we should bump the minimum version and update any dependencies https://nodejs.org/en/blog/announcements/nodejs16-eol

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
done in #600
