### ISSUE TITLE
Polylang hreflang links missing

### ISSUE THREAD

**Issue by lucymtc** [10up/headstartwp#686]
### Describe the bug

The polylang plugin hooks into wp_head to add hreflang links to output references to translated pages. wp_head is a front end hook, therefore needs a different implementation for nextjs app.

### Steps to Reproduce

1. Run headstartwp locally.
2. Make sure Polylang is enabled and languages added. 
3. Create a Page and a translated version.
4. Run FE via WP on localhost:8888 and visit the page. 
5. View source code and check the output of hreflang links exists. 
6. Run the FE on nextjs localhost:3000 and view source code on the same page. 
7. hreflang links are missnig.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lucymtc** [comment]
@nicholasio this is fixed on a client project through hooking into `wpseo_frontend_presenters` to add the hreflang presenter.

**Comment by nicholasio** [comment]
@lucymtc would love to se a PR with that fix! I think it makes sense to fix this in the wp plugin.
