### ISSUE TITLE
Menu item ID is not necessarily a number 

### ISSUE THREAD

**Issue by Knskan3** [10up/headstartwp#772]
https://github.com/10up/headstartwp/blob/77764a99717598373177dd6c98df0c9d050a17d9/packages/core/src/react/hooks/useFetchMenu.ts#L21

When using polylang, the menu item ID could contain the `id-LANG`, causing errors during the Number cast.

In example: 
<img width="565" alt="Screenshot 2024-05-20 at 16 14 57" src="https://github.com/10up/headstartwp/assets/1422357/40adfd4e-618c-4efa-a63b-77e8fa63d7e4">

**Comment by nicholasio** [comment]
Thanks for the bug report
