### ISSUE TITLE
When using getServerSideProps with addHookData the page loses the usePost info

### ISSUE THREAD

**Issue by Knskan3** [10up/headstartwp#774]
### Describe the bug

When using getServerSideProps with addHookData the page loses the usePost info

### Steps to Reproduce

Context: 
- using `getServerSideProps` (full SSR site)
- I have to extend the  `addHookData` with props to manually inject the`usePost` result, otherwise, it's removed.

<img width="711" alt="Screenshot 2024-05-21 at 07 47 05" src="https://github.com/10up/headstartwp/assets/1422357/56bfd698-0d0f-41d4-a0f1-387a90df5d30">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
When you say "the page loses the usePost info" do you mean you are not able to use `usePost` hook?

By design you should not be able to access the post data directly from props but only from the hooks.

**Comment by nicholasio** [comment]
In the pages router, you need to pass the exact same params both on the server and on the client, see the example here: https://github.com/10up/headstartwp/blob/develop/projects/wp-nextjs/src/pages/%5B...path%5D.tsx#L106
