### ISSUE TITLE
ACF fields missing in the menu REST payload.

### ISSUE THREAD

**Issue by Knskan3** [10up/headstartwp#775]
https://github.com/10up/headstartwp/blob/4744f560bbb914a163e2575997b787fbf71e58b8/wp/headless-wp/includes/classes/API/AppEndpoint.php#L210

The current implementation doesn't include the ACF fields to the menu items. 

When using ACF, here's a solution to add the fields.

```php
			$acf_fields = get_fields($menu_item->ID);
			$filtered_menu_item->acf = $acf_fields;
```

**Comment by nicholasio** [comment]
We don't provide an official integration with ACF but you can extend the app endpoint through `headless_wp_api_app_response` and add the fields you need. https://github.com/10up/headstartwp/blob/4744f560bbb914a163e2575997b787fbf71e58b8/wp/headless-wp/includes/classes/API/AppEndpoint.php#L170
