### ISSUE TITLE
How to get the translation strings from polylang

### ISSUE THREAD

**Issue by Knskan3** [10up/headstartwp#776]
### Describe your question

During the implementation of the site, we might need to define string translations to be used in the template.
How can we manage and GET the translation strings? I don't see any hook for this. 
Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
The framework doesn't have a native way to fetch polylang strings, what you could do is extend the app endpoint and include the polylang stirngs on the WP side via this [filter](https://github.com/10up/headstartwp/blob/develop/wp/headless-wp/includes/classes/API/AppEndpoint.php#L170)

Then, if you are using TypeScript I'd recommend doing this: https://headstartwp.10up.com/docs/learn/data-fetching/creating-your-own-custom-hooks/#creating-your-own-appsettings-hook

**Comment by Knskan3** [comment]
I'll give it a try thanks 👍
