### ISSUE TITLE
images.domains deprecation

### ISSUE THREAD

**Issue by Antonio-Laguna** [10up/headstartwp#812]
### Describe the bug

Upon running Next with no extra config

```
 ⚠ The "images.domains" configuration is deprecated. Please use "images.remotePatterns" configuration instead.
```

### Steps to Reproduce

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
Ideally we would have a way to detect the next.js version and adjust the config accordingly to avoid doing a major just for this setting.

**Comment by nicholasio** [comment]
https://github.com/10up/headstartwp/issues/655
