### ISSUE TITLE
When ServerRelatedPosts fails, queryPosts throws an error

### ISSUE THREAD

**Issue by sambrodie** [10up/headstartwp#842]
### Describe the bug

In wp-nextjs-app:

Even if the main query is working, the error from the `ServerRelatedPosts` component will override the output of the main query and display an error.

Can we safely add `options: { throwIfNotFound: false }` to the queryPosts call in `ServerRelatedPosts` to suppress this error?

### Steps to Reproduce

1) Create a site with only one post
2) Visit that post

### Screenshots, screen recording, code snippet

https://share.zight.com/kpuv9Pqg

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
Fixed in https://github.com/10up/headstartwp/commit/aaf7b8f726f282bdcbb52b57aceb9e3b4d7937ca
