### ISSUE TITLE
Build fails due to Link component's type

### ISSUE THREAD

**Issue by tcmulder** [10up/headstartwp#847]
### Describe the bug

After initial setup, `npm run build` fails for me with the following error: "Type error: Type '({ href, rel, children, target, className }: LinkProps) => JSX.Element' is not assignable to type 'ReactNode'."

### Steps to Reproduce

1. Run `npx create-next-app --use-npm -e https://github.com/10up/headstartwp/tree/trunk/projects/wp-nextjs` and `cd` into the directory it creates.
2. Duplicate .env as .env.local and enter details for a new local WordPress install with the HeadstartWP plugin installed and activated.
3. Run `npm run build`.
4. See the error.

### Screenshots, screen recording, code snippet

![Screenshot 2024-08-09 at 8 55 43 AM](https://github.com/user-attachments/assets/9c388a5b-f60a-452b-98b9-5e8d6ea1dc72)

### WordPress information

- WordPress:  v6.6.1
- HeadstartWP: v1.1.3
- Host: LocalWP

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
Thanks for the bug report. We'll look into it. In the meantime, you can add `// @ts-expect-error` to make it build.

**Comment by tcmulder** [comment]
Perfect, thanks for the quick reply!
