### ISSUE TITLE
Backward Compatibility Issue Sitemap and Robot.txt

### ISSUE THREAD

**Issue by MohammedNagdy** [10up/headstartwp#853]
### Describe the bug

Our website has been getting this error for robots.txt and sitemap
```Javascript
Server Error
Error: socket hang up

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
connResetException
node:internal/errors (691:14)
TLSSocket.socketCloseListener
node:_http_client (420:25)
TLSSocket.emit
node:events (402:35)
<unknown>
node:net (687:12)
TCP.done
node:_tls_wrap (580:7)
```
This could be to a number of reasons but the main problem I suspect is that the rewrites in this [PR](https://github.com/10up/headstartwp/pull/313) don't exist anymore. Please could you confirm on that?

### Steps to Reproduce

1. Check the robots.txt and sitemap that should be rewritten to your (Nextjs) frontend domain

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
That rewrite is still in the codebase https://github.com/10up/headstartwp/blob/trunk/packages/next/src/config/withHeadstartWPConfig.ts#L173

Can you share the link for your Next.js and WP backend?

**Comment by nicholasio** [comment]
I have not been able to reproduce this issue. Can you provide more information about your setup? Are you using the Yoast SEO plugin? What's the headstartwp version?

**Comment by MohammedNagdy** [comment]
I am sorry for the late response. It turned out the issue was caused by our own setup. We had two proxies on top of each a domain proxy through cloudflare and a slow server that wasn't able to process the rewrite somehow. So I don't it's caused by the rewrites.
